"""Generated clone installers. Never edit the committed adapter outputs."""
from __future__ import annotations

import json
from string import Template

from ..install.agent_skills_projection import MANIFEST_NAME, agent_skills_manifest
from .host_adapters import HOST_ADAPTERS, checksum_inventory, host_adapter_manifest


_SH = Template(r'''#!/bin/sh
# Generated by omh docs agent-skills; edit the catalog/producer, not this file.
# Source inventory SHA256: $digest
set -eu
fail() { printf '%s\n' "$$*" >&2; exit 1; }
scope=repo
case $$# in
    0) ;;
    1) [ "$$1" = --user ] || fail 'Usage: install.sh [--user]'; scope=user ;;
    *) fail 'Usage: install.sh [--user]' ;;
esac
base=$$(pwd -P)
if [ "$$scope" = user ]; then
    [ -n "$${HOME:-}" ] || fail 'HOME is required for --user'
    base=$$(CDPATH= cd -- "$$HOME" && pwd -P)
    target="$$base/$user_path"
else
    target="$$base/$repo_path"
fi
source="$$(dirname -- "$$0")/../agent-skills"
[ ! -L "$$source" ] || fail 'Symlink source root'
source=$$(CDPATH= cd -- "$$source" && pwd -P)
if command -v sha256sum >/dev/null 2>&1; then
    checksum() { sha256sum "$$@"; }
elif command -v shasum >/dev/null 2>&1; then
    checksum() { shasum -a 256 "$$@"; }
else
    fail 'SHA256 verification requires sha256sum or shasum'
fi
checksums=$$(cat <<'OMH_CHECKSUMS'
$checksums
OMH_CHECKSUMS
)
paths=$$(cat <<'OMH_PATHS'
$paths
OMH_PATHS
)
# Reject extra files and links rather than silently installing an unverified tree.
[ -z "$$(find "$$source" ! -type f ! -type d -print)" ] || fail 'Unsupported source entry (including symlink)'
actual=$$(cd "$$source" && find . -type f -print | LC_ALL=C sort)
expected=$$(printf '%s\n' "$$paths" | while IFS= read -r path; do printf './%s\n' "$$path"; done)
[ "$$actual" = "$$expected" ] || fail 'Source file inventory mismatch'
verify() {
    printf '%s\n' "$$checksums" | (cd "$$1" && checksum -c -) >/dev/null || fail 'Skill digest mismatch'
}
verify "$$source"
# Preflight EVERY target before the first write, including the receipt.
# Do not follow destination links.
printf '%s\n' "$$paths" '$receipt_name' | while IFS= read -r path; do
    current="$$target/$$path"
    while [ "$$current" != "$$base" ]; do
        [ ! -L "$$current" ] || fail "Symlink destination: $$current"
        current=$${current%/*}
        [ -n "$$current" ] || current=/
    done
    [ ! -e "$$target/$$path" ] || [ -f "$$target/$$path" ] || fail "Not a file: $$target/$$path"
done
printf '%s\n' "$$paths" | while IFS= read -r path; do
    mkdir -p "$$target/$${path%/*}"
    cp "$$source/$$path" "$$target/$$path"
done
verify "$$target"
cat > "$$target/$receipt_name" <<'OMH_RECEIPT'
$receipt
OMH_RECEIPT
printf 'Installed $host skills in %s\n' "$$target"
cat <<'OMH_SKILLS'
$skills
OMH_SKILLS
''')

_PS1 = Template(r'''# Generated by omh docs agent-skills; edit the catalog/producer, not this file.
# Source inventory SHA256: $digest
param([switch]$$User)
$$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
if ($$args.Count) { throw 'Usage: install.ps1 [-User]' }
$$base = (Get-Location).ProviderPath
if ($$User) {
    $$base = $$env:USERPROFILE
    if (-not $$base) { $$base = $$env:HOME }
    if (-not $$base) { throw 'User profile is required for -User' }
    $$target = Join-Path $$base '$user_path'
} else {
    $$target = Join-Path $$base '$repo_path'
}
$$source = Join-Path (Split-Path -Parent $$PSScriptRoot) 'agent-skills'
$$checksums = @'
$checksums
'@
$$entries = @($$checksums.Split("`n") | ForEach-Object {
    $$parts = $$_.TrimEnd("`r") -split '  ', 2
    [PSCustomObject]@{ Path = $$parts[1]; Hash = $$parts[0] }
})
function Assert-NoLink([string]$$Path, [string]$$Boundary) {
    $$current = $$Path
    while ($$current -and $$current -ne $$Boundary) {
        if (Test-Path -LiteralPath $$current) {
            $$item = Get-Item -Force -LiteralPath $$current
            if ($$item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
                throw "Reparse-point path: $$current"
            }
        }
        $$current = Split-Path -Parent $$current
    }
}
Assert-NoLink $$source (Split-Path -Parent $$source)
$$items = @(Get-ChildItem -Force -Recurse -LiteralPath $$source)
foreach ($$item in $$items) {
    if ($$item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
        throw "Reparse-point source: $$($$item.FullName)"
    }
}
$$sourceFiles = @($$items | Where-Object { -not $$_.PSIsContainer })
if ($$sourceFiles.Count -ne $$entries.Count) { throw 'Source file inventory mismatch' }
function Assert-Digests([string]$$Root) {
    foreach ($$entry in $$entries) {
        $$path = Join-Path $$Root $$entry.Path
        if (-not (Test-Path -LiteralPath $$path -PathType Leaf)) { throw "Missing skill: $$path" }
        if ((Get-FileHash -LiteralPath $$path -Algorithm SHA256).Hash.ToLowerInvariant() -cne $$entry.Hash) {
            throw "Skill digest mismatch: $$path"
        }
    }
}
Assert-Digests $$source
# Preflight the receipt as well as every copied file before any write.
foreach ($$relative in (@($$entries.Path) + '$receipt_name')) {
    $$path = Join-Path $$target $$relative
    Assert-NoLink $$path $$base
    if ((Test-Path -LiteralPath $$path) -and -not (Test-Path -LiteralPath $$path -PathType Leaf)) {
        throw "Not a file: $$path"
    }
}
foreach ($$entry in $$entries) {
    $$path = Join-Path $$target $$entry.Path
    [IO.Directory]::CreateDirectory((Split-Path -Parent $$path)) | Out-Null
    [IO.File]::Copy((Join-Path $$source $$entry.Path), $$path, $$true)
}
Assert-Digests $$target
$$receipt = @'
$receipt
'@
# Match the CLI's UTF-8 without BOM and LF bytes even on Windows PowerShell 5.1.
[IO.File]::WriteAllText((Join-Path $$target '$receipt_name'),
    $$receipt.Replace("`r`n", "`n") + "`n", [Text.UTF8Encoding]::new($$false))
Write-Output "Installed $host skills in $$target"
@'
$skills
'@ -split "`n"
''')


def host_adapter_files(files: dict[str, str]) -> dict[str, str]:
    """All 18 committed files derive from the same source inventory/host rows."""
    result = {}
    receipt = json.dumps(agent_skills_manifest(files), indent=2, sort_keys=True)
    for adapter in HOST_ADAPTERS:
        manifest = host_adapter_manifest(adapter.host, files)
        fields = {
            "host": manifest["host"],
            "receipt_name": MANIFEST_NAME,
            "receipt": receipt,
            "digest": manifest["source_digest"],
            "repo_path": manifest["targets"]["repo"],
            "user_path": manifest["targets"]["user"],
            "checksums": checksum_inventory(manifest["files"]).rstrip("\n"),
            "paths": "\n".join(manifest["files"]),
            "skills": "\n".join(manifest["skills"]),
        }
        result[f".{adapter.host}/install.sh"] = _SH.substitute(fields)
        result[f".{adapter.host}/install.ps1"] = _PS1.substitute(fields)
        result[f".{adapter.host}/manifest.json"] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    return result
