#!/bin/sh
# Generated by omh docs agent-skills; edit the catalog/producer, not this file.
# Source inventory SHA256: 46e8481b14c750d2d67e650661fe8c9bffd1cf30bc9cc874030db1199eefce85
set -eu
fail() { printf '%s\n' "$*" >&2; exit 1; }
scope=repo
case $# in
    0) ;;
    1) [ "$1" = --user ] || fail 'Usage: install.sh [--user]'; scope=user ;;
    *) fail 'Usage: install.sh [--user]' ;;
esac
base=$(pwd -P)
if [ "$scope" = user ]; then
    [ -n "${HOME:-}" ] || fail 'HOME is required for --user'
    base=$(CDPATH= cd -- "$HOME" && pwd -P)
    target="$base/.agents/skills"
else
    target="$base/.agents/skills"
fi
source="$(dirname -- "$0")/../agent-skills"
[ ! -L "$source" ] || fail 'Symlink source root'
source=$(CDPATH= cd -- "$source" && pwd -P)
if command -v sha256sum >/dev/null 2>&1; then
    checksum() { sha256sum "$@"; }
elif command -v shasum >/dev/null 2>&1; then
    checksum() { shasum -a 256 "$@"; }
else
    fail 'SHA256 verification requires sha256sum or shasum'
fi
checksums=$(cat <<'OMH_CHECKSUMS'
cdc1844d1c39da38d4b2741cf9c5898ae37467780ac6916486dba91c2baa0aac  omh-accessibility-audit/SKILL.md
cd7e0404576923cfd3bcec9e055b1de7a78f3fc55971fd033598aac1043e4469  omh-accessibility-audit/references/a11y-rules.md
e594c276604fae664714ac16357842c08a3749ea97251cc747ae54cee3a02799  omh-adversarial-consensus/SKILL.md
e2337062d98214abc440d3909d7c076db284c817dc45c9b67a292003a6b51a89  omh-adversarial-consensus/references/consensus-protocol.md
2e3fb852517b0a6ed3b1255dce14b4f9b3041fd0d43d1689617a95283100a7cd  omh-agent-debug/SKILL.md
aa1b9e4776c78c48f0f45d17589090605a2bbdc413b61365a512cf63e5ee3eac  omh-agent-ops-review/SKILL.md
d9dab70027ab489a122df7e5814e9580e6bc1cc1899fa70da680ef54bfd65291  omh-agent-ops-review/references/instrumentation-ladder.md
1d372b27f000c7d94ba9ca91fd85386d5dbf1e0f2f102f7676534cc9a3514fe2  omh-ai-slop-cleaner/SKILL.md
d713b686c3cc076cbba63aa278176581dc09aae94c07697c3413e8d124c5845d  omh-ai-slop-cleaner/references/cleanup-passes.md
efd209984c3e5823995484dd5b6e38e3161a059db9e841b4599dbbd330417ee5  omh-ai-slop-cleaner/references/prose-lexicon.md
de930904bbca05f8e5a891686c74d0b2cf7497a3ceeabd683d363b6bd42485e7  omh-apple-design/SKILL.md
09588fbd807e527ed354fc317fc0fc3c654006878da42eb59461e45fb1ad9c26  omh-apple-design/references/materials-and-accessibility.md
4984a8f9f3eb0b1876be5b4f4bc024b002c8738be53ccaa1dc29467d3aaeffa0  omh-apple-design/references/platform-foundations.md
835383a0c276a0e5150a9a7ba633bcb798d265eb5fcd96ab082dc5c513ccf5cd  omh-apple-design/references/product-visual-production.md
c021e7c05152b68d746dcea05942fd0215630551a2a419fb9fa6a809f0b6f604  omh-apple-design/references/review-playbook.md
81ac6fd49dc78ea629cc949d9d0aed99eea969629d3606866882988f5ec5e99e  omh-apple-design/references/web-production-libraries.md
5580ce22ff2c9bd6e7360c2a4382f4fd2ddbbf43c78c42af56aabc34c12c65b7  omh-application-threat-model/SKILL.md
ed3819fecf9c8d7208a49fbbebc5863dcc9df009a663e0d012431bc3296e5e8e  omh-application-threat-model/references/threat-model-method.md
74cb97f9d3b67d48ca3b175b2f3196541f617205a9a7d6899c9d1b886994217e  omh-apps/SKILL.md
4517ca767bce7a2d516a6b85606ccb9e29082de6a3a33b6ce875343974f804c6  omh-ask/SKILL.md
335bf4534ed74dfa22127c57ce121127489b1b619bf98c1e53c739ae022db2f7  omh-award-bar-score/SKILL.md
3eb04c94402da5efaa2d3bc18bb66acd1121b234a8b82a47a878c5d01725be50  omh-award-bar-score/references/award-judging-model.md
dd9aff22835c08775af87cf576b14601f92cf1c6e0a807f3fa3199d4876f9874  omh-backend/SKILL.md
843ec98391847e3de4e28057ab4aeb95d24a4d8e593b1c812e630723a4f006b9  omh-backend/references/consumer-impact.md
e20aebd284f51d18962e28959b2e35702c9662e4d3d13fb1854c60f1279a6054  omh-backend/references/schema-migration.md
984cd9cb634b88a505cbd76214e281b2e22edf3d75fc6a3b9a0a88fcc4a265f5  omh-backend/references/service-contract.md
96561eb5def9012b310c65e79866ce2902921710c7c3f6a58160586b2add0490  omh-build-failure-triage/SKILL.md
4232ba75db18e7b6083b5e35f3db44381bdf4c94fe41817e1ecb76099280dd69  omh-cancel/SKILL.md
708360a55af99d6715a6f0d413ad07a36091c9342632e15c1f140481f0fe4133  omh-code-review/SKILL.md
6a155bc585a17cb85a5bea62c5b834657e308a3958c317d54657ab0f8fcab424  omh-code-review/references/review-dispatch.md
fb2ae13bd37473da0937c715db313142d5f5516fe0b4235038b38b0ad28d7d4f  omh-code-review/references/review-lenses.md
9da4fc0d81fb7c7d26ecf6fbcf17f8ee95fc76bfba8a31f70cf689ee296682db  omh-code-review/references/review-response.md
99afc82c29fee000b31fe6749d3fe6148920de1cc24738df57bf06d0c4d0d2be  omh-code-review/references/smell-baseline.md
56cdc081b47a6f624dd1f29b68463aa8f9927af8e18890b84b0287e30e9387f5  omh-codebase-onboarding/SKILL.md
9562f69f0f9e19a2d2e6bc74cc2460a97292ee765fa76621dc21ffba1e74d8cb  omh-codebase-uml/SKILL.md
ce2ab1fe39bd5c5529ae51888b75206eda4ee4743a5b13dce00267261a935ac0  omh-codegraph-refresh/SKILL.md
775ba054ae0a85d57c9de2a134f2491205f3b5897932ef08653d03e20895859f  omh-content-operator/SKILL.md
a81698b675f07ba671b823a198f36dc8cf4f3185693e443659044b29d03a9312  omh-context-budget-review/SKILL.md
bdac27120964aa692bd9b47f107fc9f19105d87f362e787e41c217d7a38d7590  omh-context-budget-review/references/cache-placement.md
665873ff9ed585f2f9a31ccdb95f692ea16363489f9cc3d8891be9831cabdc08  omh-cto-loop/SKILL.md
ec8954a9a00cafffde68e7b38593fdd5016360faa674dfb17234c93aff250160  omh-curriculum-design/SKILL.md
5078d35c8cd9cae8257fd14fa8ab7466bff5287500f160787633ec2930d1da1b  omh-curriculum-design/references/procedure.md
4a23455b1896a722a5cf96a97d942d63e33c590e2f1f154ae008bd3098da1382  omh-data-analysis/SKILL.md
a37b5d7f993d3997df757da09d84a40cc7420d5f5705e1856e7bd1b7774b46bf  omh-decide/SKILL.md
5f017b357b0bfb37279918098b9992c3c793ac8ad4056969bf3e2c0e6d5bb9ae  omh-decide/references/capacity-planning.md
4da873d3351a8d7ab96d44860c62d7d18130147abb7aa390078eee6dbe2d4d2d  omh-decide/references/decision-records.md
a5668c92f3715a0ee64d6f3b2e01009f88165f44dd52b487a8b01128995ab145  omh-decision-prototype/SKILL.md
53334fb4c76acb18a49272bd9dfab9317c0f9d3eb812b7ef9e87550d99762e88  omh-decision-prototype/references/procedure.md
c91f7278045b9e8a439e45abcd7ee6254312cd3072bd2c9530497a0c36e0352f  omh-decision-recall/SKILL.md
42dd069b5698f64f98fed47df9459e003844c921f001a34936337e8c75b109d1  omh-deliverable-package/SKILL.md
dd898a0334429e739a99164154dd8379a7bd134ece141538f25e8b19cdb32d90  omh-deploy-and-monitor/SKILL.md
7fc7456ab024564c410205fa984b4ca537476b2bede97464cbd07d3ec6a70040  omh-design-orchestration/SKILL.md
db2bbc0adca8aeac65b420be7e31b7bd73d2127a363f1508ca140f0db6c84281  omh-design-quality-gate/SKILL.md
7b7bde56a390431bd46b1b1d3965723521c722f461d12bdc993407a54595e9ae  omh-design-quality-gate/references/design-critique-rubric.md
72fb556364daec84c8788a672b532aedc769c371556c6f8eb8410b517a2b4a39  omh-docs/SKILL.md
aef952d61200a153eeeaac29105d2baa57ebe4c8e2c026b78de79de4b02b401e  omh-external-connector-readiness/SKILL.md
b6eda7efc3307d8bd6540bec47b2564f3e565da5ad8133bd998b2ebcabdf29a3  omh-external-connector-readiness/references/memory-provider-trial.md
242b0333938a14401002ec87ce67902d1fef71d795de835eb422154dc3714271  omh-failure-signal-audit/SKILL.md
8088ee5887cfe7e8d1f093cb736802a18fe1b60f038904848d039d22e713c304  omh-feedback-triage/SKILL.md
7c02c686ce587948801fd32fb4ce45c5c37fd353edcc86e76cf51e1b11de0d1b  omh-files/SKILL.md
616784be6b01ad2b64be56c8ad709778f7e680df58b89084478e90230ea9cfb8  omh-finance-analysis/SKILL.md
0fd8b3ad528d10aebd971c26375de9775e95429d3dbdc3a6f2ee5cc063a9c79c  omh-finance-analysis/references/procedure.md
902e4ad75f3d11a301e1f12d619f3c529e2efd89603d8f10203af3684cf64ed2  omh-frontend-refactor/SKILL.md
ce187b2323fda67fb536249193b4cc0bab1f04024986c8313bb7a4c5fd87e54f  omh-frontend-refactor/references/refactor-passes.md
04084cfd8d849f9e0b468d8a30fecc58f8c37ca5d5585afeb1e3bce95719faa4  omh-frontend-refactor/references/state-discipline.md
08da747dcf7b47489e66397a7a6b6c31a8d2b1536aa3f7e0993388e0c9424afa  omh-frontend/SKILL.md
5ed9f05a8eb6d5c8ae839313f9adbae7c18b15940777645924fdb2670b64a60c  omh-frontend/references/design-system-contract.md
b36dedde2f859f83a95563cddab06f4002ce8c0a2c3b4ef64abc8a954c1e12bf  omh-frontend/references/reference-token-extraction.md
ddaaf841a154130222c98945d070f4a8b157a564ef59a3f960a3e48e01113e09  omh-frontend/references/screenshot-loop.md
605393baaed428e2adab937fdbc1ab3e5db20a6592039d948a2447da80ceb245  omh-frontend/references/scroll-motion-libraries.md
2d4552c2ae32e0e1a18517d3faf74c016cdc1c946263201118cd27ccfb2a68d7  omh-frontend/references/taste-foundations.md
13153858bf9da970915003cb22b42ff714fdfd351458f1a0cac20fd789fb477e  omh-frontend/references/tui-craft.md
7905f7913ff835eb84e7b9bd88059d52d7ede370312f2e24df8cb7ebf407a29b  omh-frontend/references/web-vitals-budgets.md
0be73e1e4c7fe6da4ee3d26148d7e04ec01abd1d838e8d1846ebc3d6ddd94695  omh-github-event-ops/SKILL.md
f8f32b8aed33fa4c21213245f4b02c31ba27616e1ee6a488252fafa1da5cbdde  omh-github-issue-intake/SKILL.md
b3b7a90e96b249b38b7f47b92aad10b9d45b070bddf43a3b84fff3ec8af02a5d  omh-harness-session-inventory/SKILL.md
d5e2cb2b5950f08d50b48e4254fd5edef7924f579e07d5b91901cd209beaba1b  omh-idea-to-deploy/SKILL.md
dc9a474dfc063984b84ae5d1a5d28a9ba1f0bb2b77292245b703b20b0fbe27e7  omh-idea-to-deploy/references/project-bootstrap.md
2b8e847cba990e39be257be7235fb865f33b9ddcbecc236fd597186bc9aed06c  omh-image-cards/SKILL.md
6439e078b9cf351699db7594759b11dadfb5c6f098307a2cb89f98ca72fded7e  omh-inference-serving/SKILL.md
31f452f33561faf2cd90edd1cf30f33bc74c14bc13c81d77a087db5392d56aa0  omh-inference-serving/references/serving-bench.md
da5b5950a621d7eedc5333721de4d23651439d06bdd2d9e9661461d1bef9ac5e  omh-inference-serving/references/serving-runbooks.md
f31526ec5dcce00e52514658379321f1b79ea30abc2163c0918e316c75ed8000  omh-instinct-ledger/SKILL.md
5c5e392c094cdbb05869c7316ac8bd9f2fa6e8c35cc7374d093b9005712c4316  omh-jit-learn/SKILL.md
65298f1e7efe6bc449ab899f841d021f5a48680e64e4cdaab64664364286bc3e  omh-legal-compliance-review/SKILL.md
a0952b301dc12976606e979590da1f01c9b71d4cd5892f6b2f453536b2e4b4c1  omh-legal-compliance-review/references/negotiation-preparation.md
670f501f3136c0f5456b82149ca24153f1b38d5151f539a9b1ab0df30e2f0b58  omh-legal-compliance-review/references/procedure.md
743a0d5bbec177edbd11560ebac72f8f455822f6c51696bfdda7ca208cccea0e  omh-lifecycle-growth/SKILL.md
7a26968cd2e4d46a536fe28d93dd7adc2f89c01ca59ab042d5d6ff205b5762de  omh-lifecycle-growth/references/procedure.md
212ef7ef9150ed589aefa732e5da3bb6d0edf876d3ea32c90ea37dcbc13a1d45  omh-live-incident-response/SKILL.md
8d5ad3bb15d401cf45300ec3d7df126072fcd20bee40e3bc702bd35027b754b7  omh-live-incident-response/references/incident-command-method.md
916e901b65fe132ecb75690277a03f59f607f719db8b49ab0d22ba24a5be9823  omh-live-info/SKILL.md
f330b0dc2fd9b2c0abbfddd079a609072565fe0a391345b2afb144cc867735e3  omh-llm-app-dev/SKILL.md
35db50a4960ced98fa2ee556e59c5a439188e8b47bebef5073efa9264d8fe149  omh-llm-app-dev/references/build-rails.md
959130e28abaabea53cf9ed6fe46268ce27372333d2a6d28b6f0e02928ac2cbd  omh-llm-app-dev/references/eval-harness.md
e69b890be7da4d91ce612722b180b229821db714bd72aa28a55db013364e7cca  omh-llm-app-dev/references/public-board.md
7bda4e79b8c60f406d3a4e7ea9d3e4f7c69d6ee80a23416678be678d6dd95816  omh-llm-app-dev/references/stateful-contracts.md
0c8e33e4957f542f7d199e64e28ca74fd940c24c33d52cfde10ea85faf4ddf64  omh-localization-review/SKILL.md
493b7175e5f16f07d0d2748cdec13ccfbdbf3e6d7a8776d25f720a82a862293b  omh-materials-package/SKILL.md
bbd0e06c25e974706cbe5b13ab1265fb52f890ead56524704d662432e4f9e2a9  omh-media-input/SKILL.md
8f9d3ceb6f417002dfb0aaca15da5dc155960e17281216e8552ec99136274bbb  omh-meeting-brief/SKILL.md
5e12394cc2785ef9a3d1f87a9445ecb451d298d70c6a049d8dbbd5eb31de696c  omh-memory-new/SKILL.md
2b9e8e683f30ba9a186a1d5c3891893c705bd70f5b59d7cef5ca0f37d15f02eb  omh-native-debugging/SKILL.md
3ce0f29395b8a1c71074ce2808d6d2497bef1ccbecbba179b74950055435430d  omh-native-debugging/references/native-debug-loop.md
d76e5206b3a5878fe4fa47307f8cf2f5853382c6bc22b336620f6a474b4e9660  omh-operating-rhythm/SKILL.md
c1cbcfaa279068b5d8f55d6e0f7077367b20c0bc5845cd7b57ce9842d86ef837  omh-ops-observability-card/SKILL.md
4d868651f134e598e7bfc44ffaea41296d779f1a3dc79d404adb5f49b6d39a05  omh-ops-review/SKILL.md
6331d4b563fce56fb3483bfd0bf7371792f4df07a83140cab1f8c13dcd3ac1c2  omh-paper-learning/SKILL.md
9458b03c26432a11c921c92730939d49d695886b759d0f6ca5b60013f1399c9a  omh-people-ops/SKILL.md
61e0c4114e57d81f1425df88a4b5589c9cfc4e53d1626a0c4387490a2013bb08  omh-physical-device-readiness/SKILL.md
ea296a28bdba65c985a266adbe5aa1dde72d5757ac70bb7bef54058dc7507250  omh-plan/SKILL.md
577991e718cf3e1d62ce93704d4a734f7e058a3d516b0722c636cc8cf7a519da  omh-plan/references/project-constitution.md
f0e97382c8dbfbb1355f76c728a9cdbbcbdbcf4dd04635ad3a894c0bf99ce2d8  omh-product-brief/SKILL.md
e4bfdeea659805425465900ed7183b82cd5b2270ac29e272cdebab09e3bccf0e  omh-product-discovery-validation/SKILL.md
c4b545ab2472299450aa8279f3d15a64afbfada6e14314f083d3f905aa52a19a  omh-product-discovery-validation/references/procedure.md
ccd2eac724a6e85e9f12a7e4ad573c02fe8d5381f273162408b5d2ef23d1d47e  omh-production-audit/SKILL.md
c623f7f0c6f7fa8a0860aaa2cddfd90a1b930fc6335abe879b3b9f4db6543ac8  omh-provider-profile-posture/SKILL.md
c64217a3d4454effedb4420f82f250e9111a77f8f2eacb0d89049948a2c72dda  omh-refactor-plan/SKILL.md
b754550de95896a85e541b5e8f7d46a45696dfa1f73afe57bf7de4df114ebac0  omh-refactor-plan/references/dependency-upgrade.md
492cfcd81b1b44ffb54bcb16b6dc319549a7ee868d95b21176fa9cc0fa06f035  omh-refactor-plan/references/refactor-phases.md
3f778a1fdd8d664c3f338d3ef96e49321f87d3b6273ae05ab00c2b0245bd2380  omh-reliability-review/SKILL.md
a2004eb4da76e31372631fc3088e389d5af287934fd004698078e0c882a969b5  omh-report-package/SKILL.md
02298e6ab6384a463ea6bef613d1de40f0d882e7059287a3962108daf92c6139  omh-research-brief/SKILL.md
72acff957c68203fe4f6cd7486fe3da0560a76209b3c44a8f15de38e32d682f9  omh-rules-distill/SKILL.md
76c08b72436283399b625950998c34f0305916fd6874e03c4e06b360ab706146  omh-run-efficiency/SKILL.md
7ea2deaecf4af7e6ee407adec268ea7acb77d0972471224de65a9273f7c2b42d  omh-running-work-board/SKILL.md
a93dfce96d4b46372fa3652929a2e6ded45c730139e930dcc86c8b0242bdeded  omh-rust/SKILL.md
7d9b5005213715f4712dac2371fa63699b8ba963e843f360d75789d576c12844  omh-rust/references/rust-discipline.md
b39328707a4c3e1cf1d152603f0840255d68db3cfda714d6c33d853ebb087768  omh-rust/references/ub-escalation.md
182e4e50739bb225a02549efe224a6854c11f75b9d181d36f854bf4b88c6e7fc  omh-sales-development/SKILL.md
0ed747dc7a21bee8931023e4f7d78f65a7a9845ccf40cd6b754eeecc2a6aea70  omh-sales-development/references/procedure.md
c91cda22518582e2b6e7be48608ecfd693a9c4631ef115ca32e27e5bdc4ba417  omh-sales-pipeline-review/SKILL.md
ae092ea4d9363da82d23620f33a2f83e8a3dd42f4a8d69fd08b92cb2989fa138  omh-sales-pipeline-review/references/procedure.md
5ac1efa0dd777bdd05b90d8f1a6a53daf198bc6f08f0587b4bdb0af6f1d71fe3  omh-security-safety-review/SKILL.md
2a4e1cacc2c10141a1aaff437353150696c397f5fec0b41536eb5d946ebff065  omh-security-safety-review/references/credential-rotation.md
00066aec1887d485e7ed687cf259d47280e672263968c2ac2e8cc5d3203ad2a0  omh-skill-health/SKILL.md
6406f2a6fa8cfe2d8961285f9de770d5d67331f152cf2a413d58300ad2928390  omh-skill-scout/SKILL.md
367c5b257680b042dd44806adfc7ac7c6408c5d7f7090410cc565b800495240c  omh-source-finder/SKILL.md
202e7bb4fadfeefc162b6a10168fe5f65cc996acecaa2347a4a7990140f3dfe1  omh-support-operations/SKILL.md
e024458d35414a484754e19fb892d6a415f2991e647e2a065ca24db8a66a7fe8  omh-tech-debt-audit/SKILL.md
7d0d601c1fc8897f0ce433dfa2ae44c2a5c9dd69ded28d7775cb6adbdd2afb75  omh-tech-debt-audit/references/debt-dimensions.md
01e07ee5f7990342db22c9a84fa4e17213fc7e45da8580114f5ddd6e65501c8c  omh-terminal/SKILL.md
40485eb8f565d29510cc15f3db89e0100511eb2f8bba6e9ab0ca8743f2dda25c  omh-toolbelt-readiness/SKILL.md
5718c92a8949a65cc6d426d7d8bc96136a2afda6d8163c722a16bc114a6a128b  omh-verification-gate/SKILL.md
91a818c86eb8311e39f7e1e0f1dca2bed5066551acff83a656aeb78e947f2fad  omh-verification-gate/references/generated-artifact-provenance.md
91b86c41bdee5e4336c92a15875f8691fb929e75377b3c18187d6bc8eb184a19  omh-verification-gate/references/requirement-coverage-map.md
40ad2652861afac03d956e7a27b673f4ab262214cb6c1855feb0f41527bbe7ee  omh-visual-qa/SKILL.md
7c803a3997dc58be0a4b88f2d7aa081cc5cac49a227d0cc19437cd1aad420759  omh-visual-qa/references/visual-verdict-contract.md
4ce0fa5bc622d16f1151dad670a7900642903753f22582e4cd93d482007af287  omh-voice-input/SKILL.md
625cac0e6e08fd6c68696accafdde7a72a1b1bcfad091d8b566669bf60921f42  omh-web-research/SKILL.md
e14a79ff7a904b9ee0d033fd9086657cc787094f4496423767a00a9da8731beb  omh-wiki/SKILL.md
6f99240689395f0b37cf57e09b4c38d1c134820271dc7cd83c6693e2c8693c5c  omh-wiki/references/wiki-blueprint.md
656b7873c4d9ad4458244bb376d4808dac9af7a520c35b6f22b58cbbe8434528  omh-wiki/references/wiki-operations.md
f13fd0b06dde204c10458cabb5d76b1f21351f7b641a73336eb82342d33ff16e  omh-wiki/references/wiki-patterns.md
672dd129e60179ed2896f454e91b4a6a3882de04104b1cbddbc20776d5058f11  omh-workspace-audit/SKILL.md
f8c0dde34375de6dc4edaaf15386f970843b1844360ef17b72d21b55ae0108e8  ulw-context/SKILL.md
122978a41c0a003f8b7a879b00c9ecc2417e75d5fbb787f24ecb3477403a67df  ulw-context/references/decision-frontier.md
0b6baee554fc8fa813d9b4b86aab55a9858441d2c3b2d90ef0d037a8f12afd45  ulw-context/references/project-terms.md
d61ea89fd5137aa0996eb0549c96643c7cd0609086bdfeaf29bd039a79b02aff  ulw-interview/SKILL.md
af4b13bcfe583b138e9b1de47a851e40e227ce30b0404fcb10bfa16abe297d3a  ulw-interview/references/ambiguity-taxonomy.md
43c24220f74c4b22a2ebb4a486ee0217a2eafd635a76f0544fc01d8365a2260f  ulw-loop/SKILL.md
e9755a82604a6b9d363716b6bf33bc980406ea40bce813d763eda9703e1a093f  ulw-loop/references/goal-constraint-discipline.md
1c3da401271e023ea21cf5aa0a1cee488cdb9bb8ca966251dc0bca767af00dfb  ulw-loop/references/measured-loop-discipline.md
604445498ecb853b724b6db642d304c55297703b749932550d5a793db1f62afd  ulw-perf/SKILL.md
f4b3c6fcf214f126bcaf07f82d159e354fcdadc2ff21fa755fa36a1036963591  ulw-plan/SKILL.md
0c9cfd860e67dc5d64a7bd902c7de6639c15fb6590455a1706a028e88d0f3bcf  ulw-qa/SKILL.md
190b4d1d4f360abcffbd8f463527d06e932fd84b6b5bc6797157ea679f89f770  ulw-research/SKILL.md
466c21fb7bedefe1e42dbdb3f8ddaf3321504882140af507a292188678243dac  ulw-research/references/briefing-format.md
bfb018d8d1c6549f6e677b2780d2c77d168347aacc795f7c3de54ced56c0de66  ulw-work/SKILL.md
b35e627344579054a9ec46722ca59cdf9f6bda41a217f0b3775669c1ad764dac  ulw-work/references/dependency-topology.md
OMH_CHECKSUMS
)
paths=$(cat <<'OMH_PATHS'
omh-accessibility-audit/SKILL.md
omh-accessibility-audit/references/a11y-rules.md
omh-adversarial-consensus/SKILL.md
omh-adversarial-consensus/references/consensus-protocol.md
omh-agent-debug/SKILL.md
omh-agent-ops-review/SKILL.md
omh-agent-ops-review/references/instrumentation-ladder.md
omh-ai-slop-cleaner/SKILL.md
omh-ai-slop-cleaner/references/cleanup-passes.md
omh-ai-slop-cleaner/references/prose-lexicon.md
omh-apple-design/SKILL.md
omh-apple-design/references/materials-and-accessibility.md
omh-apple-design/references/platform-foundations.md
omh-apple-design/references/product-visual-production.md
omh-apple-design/references/review-playbook.md
omh-apple-design/references/web-production-libraries.md
omh-application-threat-model/SKILL.md
omh-application-threat-model/references/threat-model-method.md
omh-apps/SKILL.md
omh-ask/SKILL.md
omh-award-bar-score/SKILL.md
omh-award-bar-score/references/award-judging-model.md
omh-backend/SKILL.md
omh-backend/references/consumer-impact.md
omh-backend/references/schema-migration.md
omh-backend/references/service-contract.md
omh-build-failure-triage/SKILL.md
omh-cancel/SKILL.md
omh-code-review/SKILL.md
omh-code-review/references/review-dispatch.md
omh-code-review/references/review-lenses.md
omh-code-review/references/review-response.md
omh-code-review/references/smell-baseline.md
omh-codebase-onboarding/SKILL.md
omh-codebase-uml/SKILL.md
omh-codegraph-refresh/SKILL.md
omh-content-operator/SKILL.md
omh-context-budget-review/SKILL.md
omh-context-budget-review/references/cache-placement.md
omh-cto-loop/SKILL.md
omh-curriculum-design/SKILL.md
omh-curriculum-design/references/procedure.md
omh-data-analysis/SKILL.md
omh-decide/SKILL.md
omh-decide/references/capacity-planning.md
omh-decide/references/decision-records.md
omh-decision-prototype/SKILL.md
omh-decision-prototype/references/procedure.md
omh-decision-recall/SKILL.md
omh-deliverable-package/SKILL.md
omh-deploy-and-monitor/SKILL.md
omh-design-orchestration/SKILL.md
omh-design-quality-gate/SKILL.md
omh-design-quality-gate/references/design-critique-rubric.md
omh-docs/SKILL.md
omh-external-connector-readiness/SKILL.md
omh-external-connector-readiness/references/memory-provider-trial.md
omh-failure-signal-audit/SKILL.md
omh-feedback-triage/SKILL.md
omh-files/SKILL.md
omh-finance-analysis/SKILL.md
omh-finance-analysis/references/procedure.md
omh-frontend-refactor/SKILL.md
omh-frontend-refactor/references/refactor-passes.md
omh-frontend-refactor/references/state-discipline.md
omh-frontend/SKILL.md
omh-frontend/references/design-system-contract.md
omh-frontend/references/reference-token-extraction.md
omh-frontend/references/screenshot-loop.md
omh-frontend/references/scroll-motion-libraries.md
omh-frontend/references/taste-foundations.md
omh-frontend/references/tui-craft.md
omh-frontend/references/web-vitals-budgets.md
omh-github-event-ops/SKILL.md
omh-github-issue-intake/SKILL.md
omh-harness-session-inventory/SKILL.md
omh-idea-to-deploy/SKILL.md
omh-idea-to-deploy/references/project-bootstrap.md
omh-image-cards/SKILL.md
omh-inference-serving/SKILL.md
omh-inference-serving/references/serving-bench.md
omh-inference-serving/references/serving-runbooks.md
omh-instinct-ledger/SKILL.md
omh-jit-learn/SKILL.md
omh-legal-compliance-review/SKILL.md
omh-legal-compliance-review/references/negotiation-preparation.md
omh-legal-compliance-review/references/procedure.md
omh-lifecycle-growth/SKILL.md
omh-lifecycle-growth/references/procedure.md
omh-live-incident-response/SKILL.md
omh-live-incident-response/references/incident-command-method.md
omh-live-info/SKILL.md
omh-llm-app-dev/SKILL.md
omh-llm-app-dev/references/build-rails.md
omh-llm-app-dev/references/eval-harness.md
omh-llm-app-dev/references/public-board.md
omh-llm-app-dev/references/stateful-contracts.md
omh-localization-review/SKILL.md
omh-materials-package/SKILL.md
omh-media-input/SKILL.md
omh-meeting-brief/SKILL.md
omh-memory-new/SKILL.md
omh-native-debugging/SKILL.md
omh-native-debugging/references/native-debug-loop.md
omh-operating-rhythm/SKILL.md
omh-ops-observability-card/SKILL.md
omh-ops-review/SKILL.md
omh-paper-learning/SKILL.md
omh-people-ops/SKILL.md
omh-physical-device-readiness/SKILL.md
omh-plan/SKILL.md
omh-plan/references/project-constitution.md
omh-product-brief/SKILL.md
omh-product-discovery-validation/SKILL.md
omh-product-discovery-validation/references/procedure.md
omh-production-audit/SKILL.md
omh-provider-profile-posture/SKILL.md
omh-refactor-plan/SKILL.md
omh-refactor-plan/references/dependency-upgrade.md
omh-refactor-plan/references/refactor-phases.md
omh-reliability-review/SKILL.md
omh-report-package/SKILL.md
omh-research-brief/SKILL.md
omh-rules-distill/SKILL.md
omh-run-efficiency/SKILL.md
omh-running-work-board/SKILL.md
omh-rust/SKILL.md
omh-rust/references/rust-discipline.md
omh-rust/references/ub-escalation.md
omh-sales-development/SKILL.md
omh-sales-development/references/procedure.md
omh-sales-pipeline-review/SKILL.md
omh-sales-pipeline-review/references/procedure.md
omh-security-safety-review/SKILL.md
omh-security-safety-review/references/credential-rotation.md
omh-skill-health/SKILL.md
omh-skill-scout/SKILL.md
omh-source-finder/SKILL.md
omh-support-operations/SKILL.md
omh-tech-debt-audit/SKILL.md
omh-tech-debt-audit/references/debt-dimensions.md
omh-terminal/SKILL.md
omh-toolbelt-readiness/SKILL.md
omh-verification-gate/SKILL.md
omh-verification-gate/references/generated-artifact-provenance.md
omh-verification-gate/references/requirement-coverage-map.md
omh-visual-qa/SKILL.md
omh-visual-qa/references/visual-verdict-contract.md
omh-voice-input/SKILL.md
omh-web-research/SKILL.md
omh-wiki/SKILL.md
omh-wiki/references/wiki-blueprint.md
omh-wiki/references/wiki-operations.md
omh-wiki/references/wiki-patterns.md
omh-workspace-audit/SKILL.md
ulw-context/SKILL.md
ulw-context/references/decision-frontier.md
ulw-context/references/project-terms.md
ulw-interview/SKILL.md
ulw-interview/references/ambiguity-taxonomy.md
ulw-loop/SKILL.md
ulw-loop/references/goal-constraint-discipline.md
ulw-loop/references/measured-loop-discipline.md
ulw-perf/SKILL.md
ulw-plan/SKILL.md
ulw-qa/SKILL.md
ulw-research/SKILL.md
ulw-research/references/briefing-format.md
ulw-work/SKILL.md
ulw-work/references/dependency-topology.md
OMH_PATHS
)
# Reject extra files and links rather than silently installing an unverified tree.
[ -z "$(find "$source" ! -type f ! -type d -print)" ] || fail 'Unsupported source entry (including symlink)'
actual=$(cd "$source" && find . -type f -print | LC_ALL=C sort)
expected=$(printf '%s\n' "$paths" | while IFS= read -r path; do printf './%s\n' "$path"; done)
[ "$actual" = "$expected" ] || fail 'Source file inventory mismatch'
verify() {
    printf '%s\n' "$checksums" | (cd "$1" && checksum -c -) >/dev/null || fail 'Skill digest mismatch'
}
verify "$source"
# Preflight EVERY target before the first write, including the receipt.
# Do not follow destination links.
printf '%s\n' "$paths" '.omh-agent-skills-manifest.json' | while IFS= read -r path; do
    current="$target/$path"
    while [ "$current" != "$base" ]; do
        [ ! -L "$current" ] || fail "Symlink destination: $current"
        current=${current%/*}
        [ -n "$current" ] || current=/
    done
    [ ! -e "$target/$path" ] || [ -f "$target/$path" ] || fail "Not a file: $target/$path"
done
printf '%s\n' "$paths" | while IFS= read -r path; do
    mkdir -p "$target/${path%/*}"
    cp "$source/$path" "$target/$path"
done
verify "$target"
cat > "$target/.omh-agent-skills-manifest.json" <<'OMH_RECEIPT'
{
  "catalog_revision": "ce50970d2eea48a7806e31be60be1064b4ee424afe5fbe5a1a43601c573997fd",
  "files": {
    "omh-accessibility-audit/SKILL.md": "cdc1844d1c39da38d4b2741cf9c5898ae37467780ac6916486dba91c2baa0aac",
    "omh-accessibility-audit/references/a11y-rules.md": "cd7e0404576923cfd3bcec9e055b1de7a78f3fc55971fd033598aac1043e4469",
    "omh-adversarial-consensus/SKILL.md": "e594c276604fae664714ac16357842c08a3749ea97251cc747ae54cee3a02799",
    "omh-adversarial-consensus/references/consensus-protocol.md": "e2337062d98214abc440d3909d7c076db284c817dc45c9b67a292003a6b51a89",
    "omh-agent-debug/SKILL.md": "2e3fb852517b0a6ed3b1255dce14b4f9b3041fd0d43d1689617a95283100a7cd",
    "omh-agent-ops-review/SKILL.md": "aa1b9e4776c78c48f0f45d17589090605a2bbdc413b61365a512cf63e5ee3eac",
    "omh-agent-ops-review/references/instrumentation-ladder.md": "d9dab70027ab489a122df7e5814e9580e6bc1cc1899fa70da680ef54bfd65291",
    "omh-ai-slop-cleaner/SKILL.md": "1d372b27f000c7d94ba9ca91fd85386d5dbf1e0f2f102f7676534cc9a3514fe2",
    "omh-ai-slop-cleaner/references/cleanup-passes.md": "d713b686c3cc076cbba63aa278176581dc09aae94c07697c3413e8d124c5845d",
    "omh-ai-slop-cleaner/references/prose-lexicon.md": "efd209984c3e5823995484dd5b6e38e3161a059db9e841b4599dbbd330417ee5",
    "omh-apple-design/SKILL.md": "de930904bbca05f8e5a891686c74d0b2cf7497a3ceeabd683d363b6bd42485e7",
    "omh-apple-design/references/materials-and-accessibility.md": "09588fbd807e527ed354fc317fc0fc3c654006878da42eb59461e45fb1ad9c26",
    "omh-apple-design/references/platform-foundations.md": "4984a8f9f3eb0b1876be5b4f4bc024b002c8738be53ccaa1dc29467d3aaeffa0",
    "omh-apple-design/references/product-visual-production.md": "835383a0c276a0e5150a9a7ba633bcb798d265eb5fcd96ab082dc5c513ccf5cd",
    "omh-apple-design/references/review-playbook.md": "c021e7c05152b68d746dcea05942fd0215630551a2a419fb9fa6a809f0b6f604",
    "omh-apple-design/references/web-production-libraries.md": "81ac6fd49dc78ea629cc949d9d0aed99eea969629d3606866882988f5ec5e99e",
    "omh-application-threat-model/SKILL.md": "5580ce22ff2c9bd6e7360c2a4382f4fd2ddbbf43c78c42af56aabc34c12c65b7",
    "omh-application-threat-model/references/threat-model-method.md": "ed3819fecf9c8d7208a49fbbebc5863dcc9df009a663e0d012431bc3296e5e8e",
    "omh-apps/SKILL.md": "74cb97f9d3b67d48ca3b175b2f3196541f617205a9a7d6899c9d1b886994217e",
    "omh-ask/SKILL.md": "4517ca767bce7a2d516a6b85606ccb9e29082de6a3a33b6ce875343974f804c6",
    "omh-award-bar-score/SKILL.md": "335bf4534ed74dfa22127c57ce121127489b1b619bf98c1e53c739ae022db2f7",
    "omh-award-bar-score/references/award-judging-model.md": "3eb04c94402da5efaa2d3bc18bb66acd1121b234a8b82a47a878c5d01725be50",
    "omh-backend/SKILL.md": "dd9aff22835c08775af87cf576b14601f92cf1c6e0a807f3fa3199d4876f9874",
    "omh-backend/references/consumer-impact.md": "843ec98391847e3de4e28057ab4aeb95d24a4d8e593b1c812e630723a4f006b9",
    "omh-backend/references/schema-migration.md": "e20aebd284f51d18962e28959b2e35702c9662e4d3d13fb1854c60f1279a6054",
    "omh-backend/references/service-contract.md": "984cd9cb634b88a505cbd76214e281b2e22edf3d75fc6a3b9a0a88fcc4a265f5",
    "omh-build-failure-triage/SKILL.md": "96561eb5def9012b310c65e79866ce2902921710c7c3f6a58160586b2add0490",
    "omh-cancel/SKILL.md": "4232ba75db18e7b6083b5e35f3db44381bdf4c94fe41817e1ecb76099280dd69",
    "omh-code-review/SKILL.md": "708360a55af99d6715a6f0d413ad07a36091c9342632e15c1f140481f0fe4133",
    "omh-code-review/references/review-dispatch.md": "6a155bc585a17cb85a5bea62c5b834657e308a3958c317d54657ab0f8fcab424",
    "omh-code-review/references/review-lenses.md": "fb2ae13bd37473da0937c715db313142d5f5516fe0b4235038b38b0ad28d7d4f",
    "omh-code-review/references/review-response.md": "9da4fc0d81fb7c7d26ecf6fbcf17f8ee95fc76bfba8a31f70cf689ee296682db",
    "omh-code-review/references/smell-baseline.md": "99afc82c29fee000b31fe6749d3fe6148920de1cc24738df57bf06d0c4d0d2be",
    "omh-codebase-onboarding/SKILL.md": "56cdc081b47a6f624dd1f29b68463aa8f9927af8e18890b84b0287e30e9387f5",
    "omh-codebase-uml/SKILL.md": "9562f69f0f9e19a2d2e6bc74cc2460a97292ee765fa76621dc21ffba1e74d8cb",
    "omh-codegraph-refresh/SKILL.md": "ce2ab1fe39bd5c5529ae51888b75206eda4ee4743a5b13dce00267261a935ac0",
    "omh-content-operator/SKILL.md": "775ba054ae0a85d57c9de2a134f2491205f3b5897932ef08653d03e20895859f",
    "omh-context-budget-review/SKILL.md": "a81698b675f07ba671b823a198f36dc8cf4f3185693e443659044b29d03a9312",
    "omh-context-budget-review/references/cache-placement.md": "bdac27120964aa692bd9b47f107fc9f19105d87f362e787e41c217d7a38d7590",
    "omh-cto-loop/SKILL.md": "665873ff9ed585f2f9a31ccdb95f692ea16363489f9cc3d8891be9831cabdc08",
    "omh-curriculum-design/SKILL.md": "ec8954a9a00cafffde68e7b38593fdd5016360faa674dfb17234c93aff250160",
    "omh-curriculum-design/references/procedure.md": "5078d35c8cd9cae8257fd14fa8ab7466bff5287500f160787633ec2930d1da1b",
    "omh-data-analysis/SKILL.md": "4a23455b1896a722a5cf96a97d942d63e33c590e2f1f154ae008bd3098da1382",
    "omh-decide/SKILL.md": "a37b5d7f993d3997df757da09d84a40cc7420d5f5705e1856e7bd1b7774b46bf",
    "omh-decide/references/capacity-planning.md": "5f017b357b0bfb37279918098b9992c3c793ac8ad4056969bf3e2c0e6d5bb9ae",
    "omh-decide/references/decision-records.md": "4da873d3351a8d7ab96d44860c62d7d18130147abb7aa390078eee6dbe2d4d2d",
    "omh-decision-prototype/SKILL.md": "a5668c92f3715a0ee64d6f3b2e01009f88165f44dd52b487a8b01128995ab145",
    "omh-decision-prototype/references/procedure.md": "53334fb4c76acb18a49272bd9dfab9317c0f9d3eb812b7ef9e87550d99762e88",
    "omh-decision-recall/SKILL.md": "c91f7278045b9e8a439e45abcd7ee6254312cd3072bd2c9530497a0c36e0352f",
    "omh-deliverable-package/SKILL.md": "42dd069b5698f64f98fed47df9459e003844c921f001a34936337e8c75b109d1",
    "omh-deploy-and-monitor/SKILL.md": "dd898a0334429e739a99164154dd8379a7bd134ece141538f25e8b19cdb32d90",
    "omh-design-orchestration/SKILL.md": "7fc7456ab024564c410205fa984b4ca537476b2bede97464cbd07d3ec6a70040",
    "omh-design-quality-gate/SKILL.md": "db2bbc0adca8aeac65b420be7e31b7bd73d2127a363f1508ca140f0db6c84281",
    "omh-design-quality-gate/references/design-critique-rubric.md": "7b7bde56a390431bd46b1b1d3965723521c722f461d12bdc993407a54595e9ae",
    "omh-docs/SKILL.md": "72fb556364daec84c8788a672b532aedc769c371556c6f8eb8410b517a2b4a39",
    "omh-external-connector-readiness/SKILL.md": "aef952d61200a153eeeaac29105d2baa57ebe4c8e2c026b78de79de4b02b401e",
    "omh-external-connector-readiness/references/memory-provider-trial.md": "b6eda7efc3307d8bd6540bec47b2564f3e565da5ad8133bd998b2ebcabdf29a3",
    "omh-failure-signal-audit/SKILL.md": "242b0333938a14401002ec87ce67902d1fef71d795de835eb422154dc3714271",
    "omh-feedback-triage/SKILL.md": "8088ee5887cfe7e8d1f093cb736802a18fe1b60f038904848d039d22e713c304",
    "omh-files/SKILL.md": "7c02c686ce587948801fd32fb4ce45c5c37fd353edcc86e76cf51e1b11de0d1b",
    "omh-finance-analysis/SKILL.md": "616784be6b01ad2b64be56c8ad709778f7e680df58b89084478e90230ea9cfb8",
    "omh-finance-analysis/references/procedure.md": "0fd8b3ad528d10aebd971c26375de9775e95429d3dbdc3a6f2ee5cc063a9c79c",
    "omh-frontend-refactor/SKILL.md": "902e4ad75f3d11a301e1f12d619f3c529e2efd89603d8f10203af3684cf64ed2",
    "omh-frontend-refactor/references/refactor-passes.md": "ce187b2323fda67fb536249193b4cc0bab1f04024986c8313bb7a4c5fd87e54f",
    "omh-frontend-refactor/references/state-discipline.md": "04084cfd8d849f9e0b468d8a30fecc58f8c37ca5d5585afeb1e3bce95719faa4",
    "omh-frontend/SKILL.md": "08da747dcf7b47489e66397a7a6b6c31a8d2b1536aa3f7e0993388e0c9424afa",
    "omh-frontend/references/design-system-contract.md": "5ed9f05a8eb6d5c8ae839313f9adbae7c18b15940777645924fdb2670b64a60c",
    "omh-frontend/references/reference-token-extraction.md": "b36dedde2f859f83a95563cddab06f4002ce8c0a2c3b4ef64abc8a954c1e12bf",
    "omh-frontend/references/screenshot-loop.md": "ddaaf841a154130222c98945d070f4a8b157a564ef59a3f960a3e48e01113e09",
    "omh-frontend/references/scroll-motion-libraries.md": "605393baaed428e2adab937fdbc1ab3e5db20a6592039d948a2447da80ceb245",
    "omh-frontend/references/taste-foundations.md": "2d4552c2ae32e0e1a18517d3faf74c016cdc1c946263201118cd27ccfb2a68d7",
    "omh-frontend/references/tui-craft.md": "13153858bf9da970915003cb22b42ff714fdfd351458f1a0cac20fd789fb477e",
    "omh-frontend/references/web-vitals-budgets.md": "7905f7913ff835eb84e7b9bd88059d52d7ede370312f2e24df8cb7ebf407a29b",
    "omh-github-event-ops/SKILL.md": "0be73e1e4c7fe6da4ee3d26148d7e04ec01abd1d838e8d1846ebc3d6ddd94695",
    "omh-github-issue-intake/SKILL.md": "f8f32b8aed33fa4c21213245f4b02c31ba27616e1ee6a488252fafa1da5cbdde",
    "omh-harness-session-inventory/SKILL.md": "b3b7a90e96b249b38b7f47b92aad10b9d45b070bddf43a3b84fff3ec8af02a5d",
    "omh-idea-to-deploy/SKILL.md": "d5e2cb2b5950f08d50b48e4254fd5edef7924f579e07d5b91901cd209beaba1b",
    "omh-idea-to-deploy/references/project-bootstrap.md": "dc9a474dfc063984b84ae5d1a5d28a9ba1f0bb2b77292245b703b20b0fbe27e7",
    "omh-image-cards/SKILL.md": "2b8e847cba990e39be257be7235fb865f33b9ddcbecc236fd597186bc9aed06c",
    "omh-inference-serving/SKILL.md": "6439e078b9cf351699db7594759b11dadfb5c6f098307a2cb89f98ca72fded7e",
    "omh-inference-serving/references/serving-bench.md": "31f452f33561faf2cd90edd1cf30f33bc74c14bc13c81d77a087db5392d56aa0",
    "omh-inference-serving/references/serving-runbooks.md": "da5b5950a621d7eedc5333721de4d23651439d06bdd2d9e9661461d1bef9ac5e",
    "omh-instinct-ledger/SKILL.md": "f31526ec5dcce00e52514658379321f1b79ea30abc2163c0918e316c75ed8000",
    "omh-jit-learn/SKILL.md": "5c5e392c094cdbb05869c7316ac8bd9f2fa6e8c35cc7374d093b9005712c4316",
    "omh-legal-compliance-review/SKILL.md": "65298f1e7efe6bc449ab899f841d021f5a48680e64e4cdaab64664364286bc3e",
    "omh-legal-compliance-review/references/negotiation-preparation.md": "a0952b301dc12976606e979590da1f01c9b71d4cd5892f6b2f453536b2e4b4c1",
    "omh-legal-compliance-review/references/procedure.md": "670f501f3136c0f5456b82149ca24153f1b38d5151f539a9b1ab0df30e2f0b58",
    "omh-lifecycle-growth/SKILL.md": "743a0d5bbec177edbd11560ebac72f8f455822f6c51696bfdda7ca208cccea0e",
    "omh-lifecycle-growth/references/procedure.md": "7a26968cd2e4d46a536fe28d93dd7adc2f89c01ca59ab042d5d6ff205b5762de",
    "omh-live-incident-response/SKILL.md": "212ef7ef9150ed589aefa732e5da3bb6d0edf876d3ea32c90ea37dcbc13a1d45",
    "omh-live-incident-response/references/incident-command-method.md": "8d5ad3bb15d401cf45300ec3d7df126072fcd20bee40e3bc702bd35027b754b7",
    "omh-live-info/SKILL.md": "916e901b65fe132ecb75690277a03f59f607f719db8b49ab0d22ba24a5be9823",
    "omh-llm-app-dev/SKILL.md": "f330b0dc2fd9b2c0abbfddd079a609072565fe0a391345b2afb144cc867735e3",
    "omh-llm-app-dev/references/build-rails.md": "35db50a4960ced98fa2ee556e59c5a439188e8b47bebef5073efa9264d8fe149",
    "omh-llm-app-dev/references/eval-harness.md": "959130e28abaabea53cf9ed6fe46268ce27372333d2a6d28b6f0e02928ac2cbd",
    "omh-llm-app-dev/references/public-board.md": "e69b890be7da4d91ce612722b180b229821db714bd72aa28a55db013364e7cca",
    "omh-llm-app-dev/references/stateful-contracts.md": "7bda4e79b8c60f406d3a4e7ea9d3e4f7c69d6ee80a23416678be678d6dd95816",
    "omh-localization-review/SKILL.md": "0c8e33e4957f542f7d199e64e28ca74fd940c24c33d52cfde10ea85faf4ddf64",
    "omh-materials-package/SKILL.md": "493b7175e5f16f07d0d2748cdec13ccfbdbf3e6d7a8776d25f720a82a862293b",
    "omh-media-input/SKILL.md": "bbd0e06c25e974706cbe5b13ab1265fb52f890ead56524704d662432e4f9e2a9",
    "omh-meeting-brief/SKILL.md": "8f9d3ceb6f417002dfb0aaca15da5dc155960e17281216e8552ec99136274bbb",
    "omh-memory-new/SKILL.md": "5e12394cc2785ef9a3d1f87a9445ecb451d298d70c6a049d8dbbd5eb31de696c",
    "omh-native-debugging/SKILL.md": "2b9e8e683f30ba9a186a1d5c3891893c705bd70f5b59d7cef5ca0f37d15f02eb",
    "omh-native-debugging/references/native-debug-loop.md": "3ce0f29395b8a1c71074ce2808d6d2497bef1ccbecbba179b74950055435430d",
    "omh-operating-rhythm/SKILL.md": "d76e5206b3a5878fe4fa47307f8cf2f5853382c6bc22b336620f6a474b4e9660",
    "omh-ops-observability-card/SKILL.md": "c1cbcfaa279068b5d8f55d6e0f7077367b20c0bc5845cd7b57ce9842d86ef837",
    "omh-ops-review/SKILL.md": "4d868651f134e598e7bfc44ffaea41296d779f1a3dc79d404adb5f49b6d39a05",
    "omh-paper-learning/SKILL.md": "6331d4b563fce56fb3483bfd0bf7371792f4df07a83140cab1f8c13dcd3ac1c2",
    "omh-people-ops/SKILL.md": "9458b03c26432a11c921c92730939d49d695886b759d0f6ca5b60013f1399c9a",
    "omh-physical-device-readiness/SKILL.md": "61e0c4114e57d81f1425df88a4b5589c9cfc4e53d1626a0c4387490a2013bb08",
    "omh-plan/SKILL.md": "ea296a28bdba65c985a266adbe5aa1dde72d5757ac70bb7bef54058dc7507250",
    "omh-plan/references/project-constitution.md": "577991e718cf3e1d62ce93704d4a734f7e058a3d516b0722c636cc8cf7a519da",
    "omh-product-brief/SKILL.md": "f0e97382c8dbfbb1355f76c728a9cdbbcbdbcf4dd04635ad3a894c0bf99ce2d8",
    "omh-product-discovery-validation/SKILL.md": "e4bfdeea659805425465900ed7183b82cd5b2270ac29e272cdebab09e3bccf0e",
    "omh-product-discovery-validation/references/procedure.md": "c4b545ab2472299450aa8279f3d15a64afbfada6e14314f083d3f905aa52a19a",
    "omh-production-audit/SKILL.md": "ccd2eac724a6e85e9f12a7e4ad573c02fe8d5381f273162408b5d2ef23d1d47e",
    "omh-provider-profile-posture/SKILL.md": "c623f7f0c6f7fa8a0860aaa2cddfd90a1b930fc6335abe879b3b9f4db6543ac8",
    "omh-refactor-plan/SKILL.md": "c64217a3d4454effedb4420f82f250e9111a77f8f2eacb0d89049948a2c72dda",
    "omh-refactor-plan/references/dependency-upgrade.md": "b754550de95896a85e541b5e8f7d46a45696dfa1f73afe57bf7de4df114ebac0",
    "omh-refactor-plan/references/refactor-phases.md": "492cfcd81b1b44ffb54bcb16b6dc319549a7ee868d95b21176fa9cc0fa06f035",
    "omh-reliability-review/SKILL.md": "3f778a1fdd8d664c3f338d3ef96e49321f87d3b6273ae05ab00c2b0245bd2380",
    "omh-report-package/SKILL.md": "a2004eb4da76e31372631fc3088e389d5af287934fd004698078e0c882a969b5",
    "omh-research-brief/SKILL.md": "02298e6ab6384a463ea6bef613d1de40f0d882e7059287a3962108daf92c6139",
    "omh-rules-distill/SKILL.md": "72acff957c68203fe4f6cd7486fe3da0560a76209b3c44a8f15de38e32d682f9",
    "omh-run-efficiency/SKILL.md": "76c08b72436283399b625950998c34f0305916fd6874e03c4e06b360ab706146",
    "omh-running-work-board/SKILL.md": "7ea2deaecf4af7e6ee407adec268ea7acb77d0972471224de65a9273f7c2b42d",
    "omh-rust/SKILL.md": "a93dfce96d4b46372fa3652929a2e6ded45c730139e930dcc86c8b0242bdeded",
    "omh-rust/references/rust-discipline.md": "7d9b5005213715f4712dac2371fa63699b8ba963e843f360d75789d576c12844",
    "omh-rust/references/ub-escalation.md": "b39328707a4c3e1cf1d152603f0840255d68db3cfda714d6c33d853ebb087768",
    "omh-sales-development/SKILL.md": "182e4e50739bb225a02549efe224a6854c11f75b9d181d36f854bf4b88c6e7fc",
    "omh-sales-development/references/procedure.md": "0ed747dc7a21bee8931023e4f7d78f65a7a9845ccf40cd6b754eeecc2a6aea70",
    "omh-sales-pipeline-review/SKILL.md": "c91cda22518582e2b6e7be48608ecfd693a9c4631ef115ca32e27e5bdc4ba417",
    "omh-sales-pipeline-review/references/procedure.md": "ae092ea4d9363da82d23620f33a2f83e8a3dd42f4a8d69fd08b92cb2989fa138",
    "omh-security-safety-review/SKILL.md": "5ac1efa0dd777bdd05b90d8f1a6a53daf198bc6f08f0587b4bdb0af6f1d71fe3",
    "omh-security-safety-review/references/credential-rotation.md": "2a4e1cacc2c10141a1aaff437353150696c397f5fec0b41536eb5d946ebff065",
    "omh-skill-health/SKILL.md": "00066aec1887d485e7ed687cf259d47280e672263968c2ac2e8cc5d3203ad2a0",
    "omh-skill-scout/SKILL.md": "6406f2a6fa8cfe2d8961285f9de770d5d67331f152cf2a413d58300ad2928390",
    "omh-source-finder/SKILL.md": "367c5b257680b042dd44806adfc7ac7c6408c5d7f7090410cc565b800495240c",
    "omh-support-operations/SKILL.md": "202e7bb4fadfeefc162b6a10168fe5f65cc996acecaa2347a4a7990140f3dfe1",
    "omh-tech-debt-audit/SKILL.md": "e024458d35414a484754e19fb892d6a415f2991e647e2a065ca24db8a66a7fe8",
    "omh-tech-debt-audit/references/debt-dimensions.md": "7d0d601c1fc8897f0ce433dfa2ae44c2a5c9dd69ded28d7775cb6adbdd2afb75",
    "omh-terminal/SKILL.md": "01e07ee5f7990342db22c9a84fa4e17213fc7e45da8580114f5ddd6e65501c8c",
    "omh-toolbelt-readiness/SKILL.md": "40485eb8f565d29510cc15f3db89e0100511eb2f8bba6e9ab0ca8743f2dda25c",
    "omh-verification-gate/SKILL.md": "5718c92a8949a65cc6d426d7d8bc96136a2afda6d8163c722a16bc114a6a128b",
    "omh-verification-gate/references/generated-artifact-provenance.md": "91a818c86eb8311e39f7e1e0f1dca2bed5066551acff83a656aeb78e947f2fad",
    "omh-verification-gate/references/requirement-coverage-map.md": "91b86c41bdee5e4336c92a15875f8691fb929e75377b3c18187d6bc8eb184a19",
    "omh-visual-qa/SKILL.md": "40ad2652861afac03d956e7a27b673f4ab262214cb6c1855feb0f41527bbe7ee",
    "omh-visual-qa/references/visual-verdict-contract.md": "7c803a3997dc58be0a4b88f2d7aa081cc5cac49a227d0cc19437cd1aad420759",
    "omh-voice-input/SKILL.md": "4ce0fa5bc622d16f1151dad670a7900642903753f22582e4cd93d482007af287",
    "omh-web-research/SKILL.md": "625cac0e6e08fd6c68696accafdde7a72a1b1bcfad091d8b566669bf60921f42",
    "omh-wiki/SKILL.md": "e14a79ff7a904b9ee0d033fd9086657cc787094f4496423767a00a9da8731beb",
    "omh-wiki/references/wiki-blueprint.md": "6f99240689395f0b37cf57e09b4c38d1c134820271dc7cd83c6693e2c8693c5c",
    "omh-wiki/references/wiki-operations.md": "656b7873c4d9ad4458244bb376d4808dac9af7a520c35b6f22b58cbbe8434528",
    "omh-wiki/references/wiki-patterns.md": "f13fd0b06dde204c10458cabb5d76b1f21351f7b641a73336eb82342d33ff16e",
    "omh-workspace-audit/SKILL.md": "672dd129e60179ed2896f454e91b4a6a3882de04104b1cbddbc20776d5058f11",
    "ulw-context/SKILL.md": "f8c0dde34375de6dc4edaaf15386f970843b1844360ef17b72d21b55ae0108e8",
    "ulw-context/references/decision-frontier.md": "122978a41c0a003f8b7a879b00c9ecc2417e75d5fbb787f24ecb3477403a67df",
    "ulw-context/references/project-terms.md": "0b6baee554fc8fa813d9b4b86aab55a9858441d2c3b2d90ef0d037a8f12afd45",
    "ulw-interview/SKILL.md": "d61ea89fd5137aa0996eb0549c96643c7cd0609086bdfeaf29bd039a79b02aff",
    "ulw-interview/references/ambiguity-taxonomy.md": "af4b13bcfe583b138e9b1de47a851e40e227ce30b0404fcb10bfa16abe297d3a",
    "ulw-loop/SKILL.md": "43c24220f74c4b22a2ebb4a486ee0217a2eafd635a76f0544fc01d8365a2260f",
    "ulw-loop/references/goal-constraint-discipline.md": "e9755a82604a6b9d363716b6bf33bc980406ea40bce813d763eda9703e1a093f",
    "ulw-loop/references/measured-loop-discipline.md": "1c3da401271e023ea21cf5aa0a1cee488cdb9bb8ca966251dc0bca767af00dfb",
    "ulw-perf/SKILL.md": "604445498ecb853b724b6db642d304c55297703b749932550d5a793db1f62afd",
    "ulw-plan/SKILL.md": "f4b3c6fcf214f126bcaf07f82d159e354fcdadc2ff21fa755fa36a1036963591",
    "ulw-qa/SKILL.md": "0c9cfd860e67dc5d64a7bd902c7de6639c15fb6590455a1706a028e88d0f3bcf",
    "ulw-research/SKILL.md": "190b4d1d4f360abcffbd8f463527d06e932fd84b6b5bc6797157ea679f89f770",
    "ulw-research/references/briefing-format.md": "466c21fb7bedefe1e42dbdb3f8ddaf3321504882140af507a292188678243dac",
    "ulw-work/SKILL.md": "bfb018d8d1c6549f6e677b2780d2c77d168347aacc795f7c3de54ced56c0de66",
    "ulw-work/references/dependency-topology.md": "b35e627344579054a9ec46722ca59cdf9f6bda41a217f0b3775669c1ad764dac"
  },
  "schema_version": "omh_agent_skills_projection/v1",
  "target_dirs": [
    "."
  ]
}
OMH_RECEIPT
printf 'Installed openclaw skills in %s\n' "$target"
cat <<'OMH_SKILLS'
omh-accessibility-audit
omh-adversarial-consensus
omh-agent-debug
omh-agent-ops-review
omh-ai-slop-cleaner
omh-apple-design
omh-application-threat-model
omh-apps
omh-ask
omh-award-bar-score
omh-backend
omh-build-failure-triage
omh-cancel
omh-code-review
omh-codebase-onboarding
omh-codebase-uml
omh-codegraph-refresh
omh-content-operator
omh-context-budget-review
omh-cto-loop
omh-curriculum-design
omh-data-analysis
omh-decide
omh-decision-prototype
omh-decision-recall
omh-deliverable-package
omh-deploy-and-monitor
omh-design-orchestration
omh-design-quality-gate
omh-docs
omh-external-connector-readiness
omh-failure-signal-audit
omh-feedback-triage
omh-files
omh-finance-analysis
omh-frontend
omh-frontend-refactor
omh-github-event-ops
omh-github-issue-intake
omh-harness-session-inventory
omh-idea-to-deploy
omh-image-cards
omh-inference-serving
omh-instinct-ledger
omh-jit-learn
omh-legal-compliance-review
omh-lifecycle-growth
omh-live-incident-response
omh-live-info
omh-llm-app-dev
omh-localization-review
omh-materials-package
omh-media-input
omh-meeting-brief
omh-memory-new
omh-native-debugging
omh-operating-rhythm
omh-ops-observability-card
omh-ops-review
omh-paper-learning
omh-people-ops
omh-physical-device-readiness
omh-plan
omh-product-brief
omh-product-discovery-validation
omh-production-audit
omh-provider-profile-posture
omh-refactor-plan
omh-reliability-review
omh-report-package
omh-research-brief
omh-rules-distill
omh-run-efficiency
omh-running-work-board
omh-rust
omh-sales-development
omh-sales-pipeline-review
omh-security-safety-review
omh-skill-health
omh-skill-scout
omh-source-finder
omh-support-operations
omh-tech-debt-audit
omh-terminal
omh-toolbelt-readiness
omh-verification-gate
omh-visual-qa
omh-voice-input
omh-web-research
omh-wiki
omh-workspace-audit
ulw-context
ulw-interview
ulw-loop
ulw-perf
ulw-plan
ulw-qa
ulw-research
ulw-work
OMH_SKILLS
